### ISSUE TITLE
The go to top button is not aligned properly

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#1019] opened 2023-06-05 12:19 UTC
### Details

The go to top button in the front page is not aligned properly.
As seen in the screenshots it's alignment is not proper.
I can change the alignment of go-to-top button so that it looks better.
Can you asssign this task to me?

### Screenshots

                                                           Original
![WhatsApp Image 2023-06-05 at 17 44 22](https://github.com/Spyware007/Animating-Buttons/assets/128773151/cd8df621-1861-4e65-a294-c89e484f97ad)

                                                          After updating
![WhatsApp Image 2023-06-05 at 17 44 46](https://github.com/Spyware007/Animating-Buttons/assets/128773151/89a8f13c-dd97-4993-8b66-691595c2b3c9)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by PoorviShetty** [comment] 2023-06-06 14:00
Duplicate of #1014

**Closed by PoorviShetty** 2023-06-06 14:00 UTC
Labels: new issue, awaiting triage
